### ISSUE TITLE
完善投票功能

### ISSUE THREAD

**Issue by 2195535283** [swearitagain/EduCnblogs2.0#125]
由吴昊、陈治齐进行

**Comment by 2195535283** [comment]
投票尚未实装功能：添加和删除选项，添加和删除问题。

**Comment by 2195535283** [comment]
[完成添加选项和问题](https://github.com/swearitagain/EduCnblogs2.0/commit/1d1feb12c8851cd0729b21e0fe7166746f2a9fd4)

**Comment by kilotron** [comment]
issue界限模糊，关闭掉
