### ISSUE TITLE
投票说明较长时，投票详情页不能完全显示投票说明和内容

### ISSUE THREAD

**Issue by kilotron** [swearitagain/EduCnblogs2.0#171]

**Comment by Welkin1027** [comment]
[https://github.com/swearitagain/EduCnblogs2.0/commit/61efac4e73cace88c08418e2a8a96bb8acfff2bc](url)

**Comment by Welkin1027** [comment]
commit记录[https://github.com/swearitagain/EduCnblogs2.0/commit/61efac4e73cace88c08418e2a8a96bb8acfff2bc](url)

**Comment by Welkin1027** [comment]
[commit记录](https://github.com/swearitagain/EduCnblogs2.0/commit/61efac4e73cace88c08418e2a8a96bb8acfff2bc)
