### ISSUE TITLE
快速多次点击投票会导致同一个投票发出多次

### ISSUE THREAD

**Issue by 2195535283** [swearitagain/EduCnblogs2.0#211]
比较容易复现，公告存在同样问题。

**Comment by Welkin1027** [comment]
投票发布中该问题已解决

**Comment by Welkin1027** [comment]
[投票发布中该问题已解决](https://github.com/swearitagain/EduCnblogs2.0/commit/190b3a23881aa5ff4cebcdd6cd22a415b7c2380d)
